### ISSUE TITLE
Space delimited parser can't handle contractions or hyphenated words

### ISSUE THREAD

**Issue by mzraly** [LuteOrg/lute-v3#101]
**Description**

There are certain punctuation characters in English and other languages that should be considered part of the word if they are in the interior of the word but should not be considered part of the word if they appear separately.

Consider contractions in English like: I'm, I've, I'll, he's, she's, can't, won't, don't, etc.

Consider hyphenated words in English like: teeter-totter, know-how, editor-in-chief, mother-in-law, non-de-plume, etc.

Fixing this will require at minimum updating the parse_para method in space_delimited_parser.py.  A first pass might allow ANY punctuation inside a sequence of non-whitespace characters , i.e. match words using the pseudo-regex

[word-char] ( [non-space]* [word-char] )?

Will have to consider some more examples with various punctuation -- colons, semicolons, quotation marks, long dashes, ellipses, parentheses, etc., and add the appropriate unit tests.

I might be able to help with this in a few days.

**To Reproduce**

Upload a book in English with text like: I'm a know-it-all.

Iterate through words.

Sequence seen is: I, m, a, know, it, all

Expected sequence: I'm, a, know-it-all

**Extra software info, if not already included in the Description:**

- OS: Linux
- Browser: Firefox
- How you've installed Lute: python
- Version: 3.0.8

**Comment by jzohrab** [comment]
I don't think the work is worth it, and that this can and should be offloaded to the user for them to add as multi-word terms.  I know it's not the best, but it keeps a lot of stuff out of the code for many languages, and is a one-time thing they need to add.  The list of hyphenated words could get long and ugly, and this is just considering English. :-)

**Comment by jzohrab** [comment]
I've marked this as won't fix, but happy to discuss options.  I feel this will turn into a pile of edge cases that will be tough to work with, and the savings for users are marginal.

**Comment by mzraly** [comment]
That's fine, but I reserve the right to take a look at it on my own if it becomes an issue with the content I look at :)  Point taken about the edge cases though.  If I do look at this it will be driven by a bunch of new unit tests.

**Comment by jzohrab** [comment]
Totally, this is open-source software, everyone can do what they like with it! :-)

I'm trying to balance inputs with moving the project forward overall, so I can't guarantee that I'll take all proposed changes to "core Lute" -- right now while so many requests and changes are coming in I need to pick and choose what to incorporate.  Cheers and good luck!

**Comment by jzohrab** [comment]
Closing this for now, as I feel that these are multi-word terms, and trying to get a good general solution will open up a whack of problems.  @mzraly if you have anything that you feel should be in "core Lute", let me know!  :wave: thanks for the issue.
