### ISSUE TITLE
QOL: Auto save child changes when clicking into parent -- blocked by #99

### ISSUE THREAD

**Issue by Mycheze** [LuteOrg/lute-v3#103]
**Is your feature request related to a problem? Please describe.**

It's very annoying to update a parent word via a child. You need to click the child, make changes, save. Click the child, click the parent, make changes, and then save. 

**Describe the solution you'd like**

It'd be really nice if, when clicking on a parent, it would just auto save any changes to the child so that it would be quicker and easier (and the annoying dialogue wouldn't pop up).

When you click a parent word, it treats it like you saved first.

**Describe alternatives you've considered**

**Additional context**

This feature would be less needed if children were "more connected" to the parent (they didn't have their own definitions, they matched learning level, etc).

**Comment by jzohrab** [comment]
Yes, it is annoying -- when I've been editing the parent, I usually just go to the parent and don't worry about the child.  Auto-save should be possible though -- I don't know if there are any issues with that.

Re matching learning level, there's an issue for that, #66, which I'd like to do soon, as I think it would be very useful.

**Comment by jzohrab** [comment]
Blocked by #99 as all terms should be created beforehand while reading a page - clarifies entity lifecycle.

**Comment by jzohrab** [comment]
#99 is done, no longer blocked.

**Comment by jzohrab** [comment]
Fixed in the `develop` branch.  On term form:

> ![Image](https://github.com/user-attachments/assets/2b3415ff-c554-405c-8b16-a93b7b74a775)

Now when a parent tag is clicked when you're on the term form (if term was edited):

> ![Image](https://github.com/user-attachments/assets/333e1a66-38c6-4ede-9787-5213f3e44b96)

the reading pane updates as usual, and the form then shows the parent term.

**Comment by jzohrab** [comment]
In `develop`, will be in next launch.

**Comment by jzohrab** [comment]
Launched in 3.5.6.
