### ISSUE TITLE
Feature request: Bulk set term status

### ISSUE THREAD

**Issue by disfated** [LuteOrg/lute-v3#12]
Just like bulk set parent, but status :)

**Comment by jzohrab** [comment]
The list of actions could get long ... perhaps could have an "actions" section that collapses similar to the filters.  Not _slick_, but not terrible either.

**Comment by jzohrab** [comment]
Added in `develop`, will be in next release.

**Comment by jzohrab** [comment]
Launched in 3.5.9.
