### ISSUE TITLE
Add the progress bar / page changer to bottom of reading page

### ISSUE THREAD

**Issue by M-Biggles** [LuteOrg/lute-v3#167]
![bar](https://github.com/jzohrab/lute-v3/assets/156795688/baf44c92-6d6f-497d-a596-9a5d704ea98c)

It would be nice to have this down the bottom too.

I don't use the 'Mark as read' feature* and would remove it in the same way as one can remove the green checkmarks, if there's a way to do so.

*I accidentally pressed it once and can't remove it (perhaps a separate issue).

**Comment by M-Biggles** [comment]
A thought: an option would be to allow the top progress bar (plus Lute logo, etc) to float at the top.

**Comment by jzohrab** [comment]
Hi there @M-Biggles - you really _should_ use the ">" character at the bottom of the page.  This marks the page as "read" but leaves unknowns as unknown.

> <img width="130" alt="image" src="https://github.com/jzohrab/lute-v3/assets/1637133/b05a9b26-2e82-4dd7-bbec-6d9ba73d26f1">

Marking pages as "read" means that you'll be able to see term usage in the texts.  See the manual: https://jzohrab.github.io/lute-manual/faq/terms/sentences-only-shown-when-page-is-read.html

Ah, but you said "I accidentally pressed it once and can't remove it (perhaps a separate issue)." -- you want to mark a page "unread"?  Right, that's not possible at the moment.

You should be able to hide both of the links at the bottom of the page using a custom style.

Floating at the top might be the best option, it would prevent duplicate page elements.  Good idea, thx.

**Comment by M-Biggles** [comment]
Yeah, @jzohrab, exactly: I'd like to be able to mark a page as 'unread'. It should remove the number of words read. Simply deducting a the number of words of the current text would be troublesome - an edit might be made to the text and the numbers could change. You'd have to record how many words were initially added when the page was marked 'read' and deduct that number.

I remember how other software would have an arrows for adding/deducting how many times you had read a text or listened to the audio. Right now it's not possible to see individual pages in the listing but could be made possible if a 'text collections' type feature were to be implemented.

**Comment by jzohrab** [comment]
Not implementing this one, it's a preference thing and I need to manage the backlog. :-)
