### ISSUE TITLE
Weird positioning of titles on reading page

### ISSUE THREAD

**Issue by M-Biggles** [LuteOrg/lute-v3#171]
I was playing around with both Latin and Hebrew script titles and how they display. There's some inconsistency. See images:

![1](https://github.com/jzohrab/lute-v3/assets/156795688/e001bc8e-e758-4d45-9f75-043b8df6c7cc)
![2](https://github.com/jzohrab/lute-v3/assets/156795688/2acc5560-43c0-47c1-9daf-cb9ee96478e0)

So, this will involve A from #165 also. I figure that the titles being displayed under the progress bar looks neater (without any further changes - it could be ok at the top, but it's too cramped at the moment).

I mentioned in #167 that you could create a floating bar. Might need a bit of a rework to fit these changes in.

**Comment by jzohrab** [comment]
Thanks for the notes and images.  Cheers!

**Comment by jzohrab** [comment]
Closing this, leaving as-is for now.  The title has been properly aligned (I think!).
