### ISSUE TITLE
Scrolling the 'Terms panel' scrolls the reading panel

### ISSUE THREAD

**Issue by M-Biggles** [LuteOrg/lute-v3#192]
![A](https://github.com/jzohrab/lute-v3/assets/156795688/f0cb0f97-d3e1-4bd6-8305-05ac85328245)

Scrolling to the bottom of this panel / box will start scrolling the text panel. It shouldn't really scroll the text unless I'm hovering over it.

**Comment by jzohrab** [comment]
I've invested a bit of time into this and can't sort out what's happening.  In an effort to manage the backlog (a wee bit), I'm closing this as nobody's brought it up!  cheers and thx MB, hope all is well.
