### ISSUE TITLE
Move page counts in text title to first column, removing chance of title conflicts

### ISSUE THREAD

**Issue by M-Biggles** [LuteOrg/lute-v3#222]
I'll be breaking up texts like this:

Book Title (1/10)
Book Title (2/10)
etc

The page counting which is automatically added to the end could conflict with book titles.

![Bug](https://github.com/jzohrab/lute-v3/assets/156795688/0a6c377f-84f4-47e7-8cc2-89825fbd9137)

My suggestion is to move the counting to the first column (where the green check goes).

**Comment by jzohrab** [comment]
Declining this for now, just to manage the backlog!
