### ISSUE TITLE
Have a list of predefined dictionaries

### ISSUE THREAD

**Issue by GrimPixel** [LuteOrg/lute-v3#230]
**Is your feature request related to a problem? Please describe.**

There are only two dictionaries to be active for a language. These two can be chosen from a large number of dictionaries.

**Describe the solution you'd like**

Have many predefined dictionary URLs, and let the user select two from them. Sentence translations too: LibreTranslate, Yandex, Baidu, and so on.

**Additional context**

List of dictionaries: https://polyglotclub.com/wiki/Language/Multiple-languages/Culture/Internet-Dictionaries

**Comment by jzohrab** [comment]
Ah nice.  A change to dictionaries is well underway #5 which will allow for many more dicts.  The dict link you gave is helpful though, thanks.

**Comment by jzohrab** [comment]
Recently lute launched a bunch of languages with dictionaries, which should be useful for new users ... effectively, that answers this issue.
