### ISSUE TITLE
Remove or make optional the ['Dictionary URI must contain ###']

### ISSUE THREAD

**Issue by emanuelps2708** [LuteOrg/lute-v3#302]
**Is your feature request related to a problem? Please describe.**
Hi jz, I'm helping to add some languages to the lute language project and in a lot of languages there are online dictionaries but they don't have a way to put ### in the link because some of them require to type the word manually

**Describe the solution you'd like**
Maybe remove the warning or make it optional

An example are the dictionaries from IDS https://ids.clld.org/ if I try to add ### it gives an error 
![image](https://github.com/jzohrab/lute-v3/assets/147004033/fad5e6a2-b82e-4690-9727-d05f8803cd3f)

**Comment by jzohrab** [comment]
Sure, optional is ok, seems like a user choice to me.  Cheers :-)

**Comment by jzohrab** [comment]
Dev size est:

- change form validation - show warning?
- check dictionary test link, test with embedded or popup
- any documentation changes?

**Comment by emanuelps2708** [comment]
Hi @jzohrab , Adrian7 (one of the contributors of the Lute Language Support Project) asked on the questions thread and Imam found a solution, it would be to create a fake parameter, for example when Adrian tried to add a Cherokee dictionary "https://www.cherokeedictionary.net/" it gave the error but adding "?lute=###" fixed it so the new link would be "https://www.cherokeedictionary.net/?lute=###". With that I think the issue is solved, just maybe if you can add this to the manual that could be very helpful, the thread link is https://discord.com/channels/1074759089051160647/1155012911299833876/1217895051926175756

**Comment by jzohrab** [comment]
Good idea @emanuelps2708 - I added that, and did that total page revision I've been putting off.  It should be up in a few minutes at https://jzohrab.github.io/lute-manual/usage/languages/dictionaries.html.

**Comment by emanuelps2708** [comment]
Thank you jz, the manual page looks amazing, great effort ;)

**Comment by jzohrab** [comment]
In 3.6.0 release.
