### ISSUE TITLE
Make the update statistics button only update the currently shown books -AKA books on the current page-

### ISSUE THREAD

**Issue by shetozz** [LuteOrg/lute-v3#303]
**Is your feature request related to a problem? Please describe.**

Currently, the stats update is too slow, specially if you have lots of books, because it updates every single one of them which is unnecessary if you're not seeing all of them anyway.

**Describe the solution you'd like**

Make it only update the currently shown books.

**Describe alternatives you've considered**

Add an update option next to each book listing.

**Comment by jzohrab** [comment]
Just wiping the stats and re-rendering the page.  The stats have been ajaxed in for a few releases now, so deleting them forces a refresh.  It's not _super_ because users can set their stats calc to a large number of pages, but it's better than it was before.

**Comment by jzohrab** [comment]
Launched in 3.5.9.
