### ISSUE TITLE
Feature request: Add status to read page

### ISSUE THREAD

**Issue by jamesdeluk** [LuteOrg/lute-v3#321]
A picture says 1000 words:

![image](https://github.com/jzohrab/lute-v3/assets/27723508/675302f5-a12d-407b-82c3-c1365f91ea12)

This was hacked together with HTML copy-paste so it doesn't actually update (and the padding/margins are a bit off) - so no useful code to be taken from this demo :)

**Comment by jzohrab** [comment]
:-)  Hi @jamesdeluk, thanks for the issue.

Is this status bar to be for just the terms on this page?

Personally, I'd find this distracting: the page already has enough colors on it, adding a summary status bar at the top adds more of the same, so this should be hide-able behind a user option with the default as "turned off".

**Comment by jamesdeluk** [comment]
> Is this status bar to be for just the terms on this page?

I'd probably prefer it to be terms for the book - in other words, a way of showing completion. For the page could also work though.

> this should be hide-able behind a user option with the default as "turned off".

That would be fine.

**Comment by jzohrab** [comment]
fyi: Currently the status bar (shown on the first page) is only a sample of the next few pages, it's not a stats bar for the full book.  There are other issues about full book stats.

**Comment by jzohrab** [comment]
Dev size estimate info:

* add bar graph - perhaps see if there's a way to extract the bar graph info from the book listing on the first page (?)
* add user option to show graph, default to false, add to "behaviour" UI (???) -- optionally, add to the default styling .css, and add a note to the custom styling page about how to show the chart.

**Comment by jamesdeluk** [comment]
I'm back with another hacking workaround 😂
https://greasyfork.org/en/scripts/493338-lute-current-page-statuses-alert-button

**Comment by jzohrab** [comment]
Ha script hacks are always great!  I have one too for opening all books.

**Comment by jzohrab** [comment]
Hi @jamesdeluk - I feel that the stats graph on the intro page is good enough for now.  If this is still a strong preference of yours LMK, but no other user has requested it, so I'm closing it just to keep the backlog sane (-ish). :-)   Cheers!

**Comment by jamesdeluk** [comment]
No worries. And for anyone else, I updated my button to a floating block: https://greasyfork.org/en/scripts/513385-lute-current-page-statuses-display
