### ISSUE TITLE
Dictionary links go away after using sentence translator

### ISSUE THREAD

**Issue by mikezraly** [LuteOrg/lute-v3#342]
**Description**

After clicking on a word in the reading page, using the "t" command to translate the sentence brings up Microsoft Bing in the right pane. After that, clicking on a word causes the right pane to become empty, and clicking on a word again brings up the usual term dialog in the top half of the right pane but does not populate the bottom half with dictionary tabs.

If after bringing up Bing with the "t" command I press the browser back-arrow I get the term dialog without dictionary tabs without the intervening blank right pane.

Workaround: (1) Go back to the main page and reload the book; (2) Hit the "h" shortcut key to switch highlights off and on.

**To Reproduce**

Steps to reproduce the behavior, e.g.:

1. Load a book
2. Click on any word
3. Use the "t" key to translate a sentence
4. Click on any word
5. Right pane is blank
6. Click on any word
7. Right pane has term entry dialog at top but but dictionary tabs below

**Screenshots**

![lute-bug-1](https://github.com/jzohrab/lute-v3/assets/152216287/5ff081c3-9ea6-4188-9eff-e6dfb51cea8f)
![lute-bug-2](https://github.com/jzohrab/lute-v3/assets/152216287/3ff6714a-33a1-4562-9809-4a759daadd03)
![lute-bug-3](https://github.com/jzohrab/lute-v3/assets/152216287/33af345a-842f-4aa6-afe3-e36f1adb957d)
![lute-bug-4](https://github.com/jzohrab/lute-v3/assets/152216287/f466f2cf-ca34-4714-9341-92ba6f7d9ccc)
![lute-bug-5](https://github.com/jzohrab/lute-v3/assets/152216287/9d17099c-6277-4147-9e67-ff09d7e5d710)

**Extra software info, if not already included in the Description:**

- OS (e.g., iOS, windows): Sonoma 14.4
- Browser (e.g., chrome, safari): Google Chrome
- How you've installed Lute (Docker, python, source): pip
- Version: 3.2.7

**Comment by jzohrab** [comment]
Thanks @mikezraly .  Can you put a backup of your db that shows this behaviour somewhere public where I can get it?  Cheers and thanks for the good write-up.

**Comment by jzohrab** [comment]
I was running into similar problems, but the recent 3.7.0 release seems to have worked this out.  @mikezraly if you update, can you confirm?

**Comment by jzohrab** [comment]
Closing due to no response. :wave:
