### ISSUE TITLE
Add default wordchars for SpaceDelimitedParser

### ISSUE THREAD

**Issue by mzraly** [LuteOrg/lute-v3#349]
**Is your feature request related to a problem? Please describe.**

Every time a new space-delimited language is added to Lute, someone needs to fill in the wordchars attribute.  If the wordchars attribute is empty, the parsing code raises an exception.  I propose to provide a generous default value for wordchars to make it easier to add new space-delimited languages without having to research the character set.

**Describe the solution you'd like**

Modify the SpaceDelimitedParser class's parse_para() method so that instead of raising an exception if wordchars is an empty string the pattern used to recognize words includes:
  - Format characters: https://www.compart.com/en/unicode/category/Cf (possibly with some exceptions)
  - Lowercase letters: https://www.compart.com/en/unicode/category/Ll
  - Modifier letters: https://www.compart.com/en/unicode/category/Lm
  - Other letters: https://www.compart.com/en/unicode/category/Lo
  - Titlecase letters: https://www.compart.com/en/unicode/category/Lt
  - Uppercase letters: https://www.compart.com/en/unicode/category/Lu
  - Spacing marks: https://www.compart.com/en/unicode/category/Mc
  - Nonspacing marks: https://www.compart.com/en/unicode/category/Mn
  - Modifier symbols: https://www.compart.com/en/unicode/category/Sk

**Describe alternatives you've considered**

Thought about adding a subclass of SpaceDelimitedParser, then realized we could just add default handling for when wordchars is empty.

**Additional context**

See discussion in General Language Support thread.

**Comment by jzohrab** [comment]
That makes a lot of sense, thanks @mzraly .  Some questions:

* How would this interact with data that users specify?
* Should this somehow be included in the Language form itself, so that if users choose "space delimited parser", these values are used to pre-populate the form fields if blank?
* Should we update all the existing languages to this?  Alternatively, should we have some way to "inherit/override" from a base template for languages?  (This seems like a lot of work)

**Comment by mzraly** [comment]
Sure:
* If there is an entry in wordchars, behavior will not change
* I think it's enough to add text "leave blank to permit all Unicode word characters"
* I think updating existing language definitions would be a good idea, once we are confident that there aren't any unexpected side effects.  I thought about suggesting adding a modified-by-user attribute to language settings so on upgrade you could replace entries whether that flag is false and maybe issue a warning if the flag is true.  I'm not sure it's worth the work.
* Rather than inherit/override I think it would be simpler to add a "clone" option to clone a language entry to create a variant for experimentation, but honestly my hope is that with this and something similar for split_sentences we could really cut down on the need to customize language settings.

**Comment by mzraly** [comment]
BTW, how do you feel about adding a dependency on https://pypi.org/project/regex/ (adding regex==2023.12.25 to requirements.txt) to add support for \p to regular expressions?

**Comment by jzohrab** [comment]
> BTW, how do you feel about adding a dependency on https://pypi.org/project/regex/ (adding regex==2023.12.25 to requirements.txt) to add support for \p to regular expressions?

Hm, per the readme, "it won't behave properly with PyPy outside U+0000..U+007F" -- this would cause problems for some langs that need 8 points.  eg cuneiform has `\U00012000-\U000123FF\U00012400-\U0001247F\U00012480-\U0001254F` -- https://jzohrab.github.io/lute-manual/usage/languages/word-characters.html#unicode-word-characters.

**Comment by mzraly** [comment]
Hmm, it seems to be working for me:

```
$ python3
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import regex
>>> p = regex.compile(r'[\p{Lo}]', regex.DEBUG)
PROPERTY MATCH GENERALCATEGORY:OTHERLETTER
>>> repr(p.search('abc123\U00012288/|-:'))
"<regex.Match object; span=(6, 7), match='𒊈'>"

```

I don't know how portable that is to earlier python versions and other OSes.  I'll look into this.  At worst I can replace the \p patterns with explicit ranges, but that will take some work.

**Comment by mzraly** [comment]
This will be fun to format in code:
* 24331 code points
* 736 ranges
* regex pattern ~ 11K

**Comment by mzraly** [comment]
@jzohrab I looked into this a bit more.  The issue is not that the *regex* package doesn't support Unicode values > 0xFFFF, it's that *pypy* (not to be confused with pypi) -- an alternative implementation of python optimized for performance -- doesn't support those Unicode values.

I would argue that Lute users are not likely to be using PyPi -- the docker deployment should be using the standard python implementation, non-technical users will be using the default python implementation, and technical users should understand the limitations of PyPy, especially if they are dealing with languages requiring the larger codepoints.

If you like I can check the output of platform.python_implementation() (see https://docs.python.org/3/library/platform.html#platform.python_implementation) at launch and add a warning if the platform is PyPy.  I think that makes more sense than maintaining code to avoid importing the regex package.

Thoughts?

**Comment by mzraly** [comment]
I tried to get a baseline by running Lute on PyPy, but "inv test" fails in tests/unit/book/test_stats.py:

```
_test_book = <[PendingRollbackError('This Session\'s transaction has been rolled back due to a previous exception during flush. To ...ters: (1,)]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)') raised in repr()] Book object at 0xbb1d718>
spanish = <[PendingRollbackError('This Session\'s transaction has been rolled back due to a previous exception during flush. To ...: (1,)]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)') raised in repr()] Language object at 0xbce8528>

    def test_stats_only_update_books_marked_stale(_test_book, spanish):
        "Have to mark book as stale, too expensive otherwise."
        add_terms(spanish, ["gato", "TENGO"])
        refresh_stats()
        assert_stats(
            ["4; 2; 50; {'0': 2, '1': 2, '2': 0, '3': 0, '4': 0, '5': 0, '98': 0, '99': 0}"]
        )
    
        add_terms(spanish, ["hola"])
        refresh_stats()
        assert_stats(
            [
                "4; 2; 50; {'0': 2, '1': 2, '2': 0, '3': 0, '4': 0, '5': 0, '98': 0, '99': 0}"
            ],
            "not updated",
        )
    
        mark_stale(_test_book)
>       refresh_stats()

tests/unit/book/test_stats.py:159: 

...

        if ret != _lib.SQLITE_OK:
>           raise self.__con._get_exception(ret)
E           sqlalchemy.exc.OperationalError: (_sqlite3.OperationalError) no such column: bookstats.id
E           [SQL: SELECT bookstats.id AS bookstats_id, bookstats."BkID" AS "bookstats_BkID", bookstats.distinctterms AS bookstats_distinctterms, bookstats.distinctunknowns AS bookstats_distinctunknowns, bookstats.unknownpercent AS bookstats_unknownpercent, bookstats.status_distribution AS bookstats_status_distribution 
E           FROM bookstats 
E           WHERE bookstats.id = ?]
E           [parameters: (1,)]
E           (Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**Comment by mzraly** [comment]
Based on previous item, I am going to proceed using the regex package for now.

**Comment by mzraly** [comment]
@jzohrab it was a failure:
```
tests/unit/book/test_stats.py ........F                                  [ 40%]
```
But yeah, it was during a flush operation:
```
_test_book = <[PendingRollbackError('This Session\'s transaction has been rolled back due to a previous exception during flush. To ...ters: (1,)]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)') raised in repr()] Book object at 0x62bef00>
```

**Comment by jzohrab** [comment]
Launched in 3.3.3
