### ISSUE TITLE
Ignore Lute's soft page break when the page is too short (less than 40%)

### ISSUE THREAD

**Issue by shetozz** [LuteOrg/lute-v3#356]
**Is your feature request related to a problem? Please describe.**

Currently, if the user manually breaks a page at the right spot, the soft page of lute can produce very short pages because of  that.

**Describe the solution you'd like**

Lute's soft page break should be ignored when the resulting page is shorter than 40% of the min character count.

**Additional context**

![Screenshot from 2024-03-19 14-40-07](https://github.com/jzohrab/lute-v3/assets/93838524/9df6a19d-5ad6-4069-a5c4-f753be81b2f6)

**Comment by jzohrab** [comment]
Dev notes:

- the current code splits by "---", and then does the page splitting.  So the code would need to potentially merge the last pages of those subdivisions ...
- maybe not as tough as I thought it would be :-) -- just needs some test cases.

**Comment by jzohrab** [comment]
Just for backlog sanity sake, I'm not going to work on this one.  There's another issue #475 , which ought to reduce these single-sentence instances.
