### ISSUE TITLE
Fix mobile reading text interactions

### ISSUE THREAD

**Issue by jzohrab** [LuteOrg/lute-v3#363]
The interactions (hover, click, drag) currently really only work on desktop.  Here's a mobile phone simulation in chrome dev tools:

> ![Image](https://github.com/jzohrab/lute-v3/assets/1637133/fa46e0de-b8b5-43f0-beb3-c0fc2510869c)

(the grey circle is where the cursor is -- I think, I'm not really sure how the simulated thing works)

For better mobile support, we could replace hover, click, and drag with tap, double-tap (or "long press"), and tap-drag respectively, though I have no idea how to do this at the moment.

refs:

* https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent#avoiding_user_agent_detection
* https://developer.mozilla.org/en-US/docs/Web/API/Touch_events

https://borstch.com/blog/javascript-touch-events-and-mobile-specific-considerations seems to have solid advice, particularly notes about the touch cancel event.

**Comment by patrickayoup** [comment]
I would prefer a long-press over double-tap. A double-tap interaction on mobile often feels awkward to me.

**Comment by jzohrab** [comment]
Long-press is better, agreed.

**Comment by jzohrab** [comment]
I've pushed branch `iss_363_wip_mobile_interactions` to the LuteOrg repo.

This _almost_ works -- 

I contacted @webofpies to see if he had any ideas.  Discord message:

Video of issue:

https://github.com/LuteOrg/lute-v3/assets/1637133/22ae7025-de29-495b-a623-bfd0e362a6a9

The video shows what's up:

* from 0:00 to 0:04, I click a term, and the form opens up as expected.
* from 0:06 to 0:08, I use long-clicks to indicate the start and end of a multiword term, and the form opens up as expected.
* Then at 0:11 I refresh the page, and from 0:14 to 0:15 I create that same term -- the form handles appear, but the form isn't shown.  I can't sort out why. 

It seems that doing an initial click to open the "regular term form" sets some kind of internal state which then influences the multiword term form opening.  If I don't do that same initial term form open, the state isn't set, and the multiword term form isn't shown properly.

**Comment by jzohrab** [comment]
The above is really a minor bug -- not a showstopper at all.

**Comment by jzohrab** [comment]
Fixed -- not perfect, but better than nothing.

Long-press to start a multi-word term, and long-press to end it.  Seems to work ok, will test on my phone.

**Comment by jzohrab** [comment]
Works on phone, not super but better than nothing :-)

**Comment by jzohrab** [comment]
Launched in 3.3.3
