### ISSUE TITLE
Back button does not reload the book status

### ISSUE THREAD

**Issue by Adriann25** [LuteOrg/lute-v3#374]
After opening a book and pressing backspace to quickly come back to the homepage, the statuses column for the book you opened disappears. As soon as the page is being refreshed, the status bar reappears.

Steps to reproduce the behavior

1. Go to any book
2. Hit backspace
3. Statuses column for that particular book is gone

Here is a short video of this behaviour in action:

https://github.com/jzohrab/lute-v3/assets/101056903/a0ad2031-a744-4e8b-b60f-5bbb0297cbd3

- OS: Windows 10
- Browser: Vivaldi (Chromium-based)
- How you've installed Lute: python
- Version: 3.2.7

**Comment by etherealite** [comment]
I'm unable to reproduce this on 3.5.0, was it fixed?
