### ISSUE TITLE
Import of children overwrites parents' status to "new"

### ISSUE THREAD

**Issue by LangNerd23** [LuteOrg/lute-v3#387]
**Description**

I downgraded to 3.2.5 in order to export the unknown words of big books I just want to start very soon.
With Lute lemma I created csv-files for parent-mapping. In that way the number of complete unknown words should be heavily reduced.

Importing the first five words to link (parents existed already) resulted in working links but the new children did not inherit the status of their parents (what I would expect to make sense). To the contrary: they children were set to "new" and the parents' status (which were previously between 4 and well know) were set to 1-New as well.

Tested both with 3.2.5 and 3.3.1

**To Reproduce**

Steps to reproduce the behavior, e.g.:

1. Go to Terms -> Input Terms
2. Upload CSV file containing headings for "term", "parent", "language", "link_status". Link_Status everywhere filled with Y. Use parents that are already in the database and have a status >1. Use checkbox "create new terms".
3. Click Import
4. Check those parents again and see how they became "new" again.

**Comment by jzohrab** [comment]
Thanks @LangNerd23 for the details.  This feels like a miss on my part: if the child record didn't have a status, it would have been set to "1" ... but then if you've set that it should link to the parent, it would have also set the parent to "1", instead of inheriting the parent status, which makes much more sense.

Thanks very much!

**Comment by jzohrab** [comment]
Thanks @LangNerd23  - I've changed the import:

* If the status is not specified, and the child is linked to the parent, the child inherits the parent status.
* If the child status is specified (and link_status is set to "y"), then the child updates the parent too on import.
* If the child new, and is imported as "unknown", but the parent already exists, then the child inherits the parent status and really is not "unknown" :-)

Phew this is tricky.  There are test specifications in `tests/features/term_import.feature`, prefixed with "Issue 387", that describe the behaviour.  I feel this is about as good as I can make it.  Thanks again for bringing this up.

**Comment by LangNerd23** [comment]
Thank you a lot! Saves me the workaround (and doesn't mess my data, when I forget about it).
Sounds pretty good.

Not sure what you meant by the last paragraph. The coding was tricky?
If it is behaving (in the next version) as you write, I don't see where it could even theoretically become better in this regard :)

**Comment by jzohrab** [comment]
Launched in 3.3.2.
