### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by Darii112** [LuteOrg/lute-v3#403]
**Description**
Cant not recognize my japanese tex showing internal error as shown in attachment

**To Reproduce**
when I create book
Steps to reproduce the behavior, e.g.:

2. Click on '...'
3. Scroll down to '...'

**Screenshots**
attached

**Extra software info, if not already included in the Description:**

- OS (e.g., iOS, windows): windows
- Browser (e.g., chrome, safari): chrome
- How you've installed Lute (Docker, python, source): python
- Version: last one

**Comment by jzohrab** [comment]
Hello @Darii112 - there's no attachment.  This is a common problem -- can you verify that you have mecab installed (https://luteorg.github.io/lute-manual/install/mecab.html) and that your Japanese language is set to use "japanese" as the parser, and not space-delimited?

**Comment by Darii112** [comment]
Sorry, Herein I am sending the attachment
![Screenshot 2024-04-22 234929](https://github.com/LuteOrg/lute-v3/assets/97657618/9975449d-2ad7-4472-8e52-8f3c195c7d99)

**Comment by Darii112** [comment]
Sorry, herein I am sending the attachment

**Comment by Darii112** [comment]
hello, meanwhile I installed medcab, while watching youtube instruction,
but error is still same

**Comment by Darii112** [comment]
This is message`s copy in command:


  Lute is running.  Open a web browser, and go to:

  http://localhost:5000

ERROR:lute.app_factory:Exception on /book/new [POST]
Traceback (most recent call last):
  File
"C:\Users\amira\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py",
line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"C:\Users\amira\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py",
line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"C:\Users\amira\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py",
line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File
"C:\Users\amira\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py",
line 865, in dispatch_request
    return
self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type:
ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"C:\Users\amira\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\lute\book\routes.py",
line 111, in new
    book = repo.add(b)
           ^^^^^^^^^^^
  File
"C:\Users\amira\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\lute\book\model.py",
line 59, in add
    dbbook = self._build_db_book(book)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"C:\Users\amira\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\lute\book\model.py",
line 85, in _build_db_book
    b = DBBook.create_book(book.title, lang, book.text,
book.max_page_tokens)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"C:\Users\amira\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\lute\models\book.py",
line 178, in create_book
    tokens = language.parser.get_parsed_tokens(segment, language)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"C:\Users\amira\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\lute\parse\space_delimited_parser.py",
line 37, in get_parsed_tokens
    return self._parse_to_tokens(clean_text, language)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"C:\Users\amira\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\lute\parse\space_delimited_parser.py",
line 70, in _parse_to_tokens
    self.parse_para(para, lang, tokens)
  File
"C:\Users\amira\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\lute\parse\space_delimited_parser.py",
line 91, in parse_para
    m = self.preg_match_capture(pattern, text)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"C:\Users\amira\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\lute\parse\space_delimited_parser.py",
line 46, in preg_match_capture
    matches = re.finditer(pattern, subject, flags=re.IGNORECASE)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program
Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\re\__init__.py",
line 224, in finditer
    return _compile(pattern, flags).finditer(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program
Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\re\__init__.py",
line 307, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program
Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\re\_compiler.py",
line 745, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program
Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\re\_parser.py",
line 979, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program
Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\re\_parser.py",
line 460, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program
Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\re\_parser.py",
line 862, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program
Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\re\_parser.py",
line 460, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program
Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\re\_parser.py",
line 573, in _parse
    code1 = _class_escape(source, this)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program
Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\re\_parser.py",
line 366, in _class_escape
    raise source.error('bad escape %s' % escape, len(escape))
re.error: bad escape \p at position 37

**Comment by jzohrab** [comment]
Edit your Japanese language and change the parser to Japanese :-). Currently it’s using space delimited, which is the problem.

**Comment by jzohrab** [comment]
Thanks for the detail above 👋

**Comment by Darii112** [comment]
THANK you soooo much .... I am crying due to happiness problem solved 🥰

**Comment by jzohrab** [comment]
Super, cheers and good luck!
