### ISSUE TITLE
bug when trying to import terms with csv file

### ISSUE THREAD

**Issue by dominiieplay** [LuteOrg/lute-v3#415]
Hi, when I try to import (russian) terms I'm getting the following: 
![Captura de tela 2024-05-11 185954](https://github.com/LuteOrg/lute-v3/assets/74380896/9ddd5638-8782-4501-bdcf-c099c754e942)
![Captura de tela 2024-05-11 190019](https://github.com/LuteOrg/lute-v3/assets/74380896/09ba8acd-a6b7-4657-b582-b174defb0a97)
and when I put the file in the formart CSV UTF-8
[Book1.csv](https://github.com/LuteOrg/lute-v3/files/15284417/Book1.csv) I'm getting:
![Captura de tela 2024-05-11 185854](https://github.com/LuteOrg/lute-v3/assets/74380896/d0abb702-ce10-4cf7-ba25-4dbd227358e5)
But the fields are correct: 
[Book1.csv](https://github.com/LuteOrg/lute-v3/files/15284410/Book1.csv)

**Comment by jzohrab** [comment]
Hi there, the file needs to be CSV (comma-separated), but your fields are semi-colon-separated.  If you import them into something like google sheets, separate to columns, and then export as comma-delimited, it should be fine.  LMK!

**Comment by dominiieplay** [comment]
> Hi there, the file needs to be CSV (comma-separated), but your fields are semi-colon-separated. If you import them into something like google sheets, separate to columns, and then export as comma-delimited, it should be fine. LMK!

You're right, thanks!
