### ISSUE TITLE
Parent status link bugs - No1 "Switch Parent – connection lost"

### ISSUE THREAD

**Issue by LangNerd23** [LuteOrg/lute-v3#416]
**Description**

When the parent for a term is switched to a new one, the parent link status gets lost after(!) saving.
(Maybe related to „parent status link bugs – No2“ that I will [post in a second](https://github.com/LuteOrg/lute-v3/issues/417))

**To Reproduce**

1. Choose a term that has had already one parent up to that point (with status_link yes)
2. Go into edit mode
3. Delete existing parent and choose a new one from drop down list (not 100% sure if that part is necessary for reproducing the error)
4. After having picked the new parent the box status_link had been automatically checked
5. Save
6. Enter again edit mode of the term from before
7. In >90% of the cases the checkbox of „link to parent“ is empty

**Extra software info, if not already included in the Description:**

- OS: Windows
- Browser: Checked both with Chrome and Firefox
- How you've installed Lute (Docker, python, source): via pip, Version 3.3.2 (couldn’t check with 3.3.3 for the reasons given on discord)

**Comment by jzohrab** [comment]
Confirmed, thanks.  On the develop branch:

existing term with existing parent, link is set

> <img width="441" alt="image" src="https://github.com/LuteOrg/lute-v3/assets/1637133/4e67bbe0-be1e-49d2-9073-740d508e8d0b">

delete that parent, link removed:

> <img width="399" alt="image" src="https://github.com/LuteOrg/lute-v3/assets/1637133/69d8a42d-8aa0-4b1c-9baf-b8db2a2b5ed5">

select new parent, link is set on the form (before save):

> <img width="430" alt="image" src="https://github.com/LuteOrg/lute-v3/assets/1637133/e11cf712-5c12-46e5-9d3f-d74a21f77f01">

After save and reopen, the checkbox was cleared (it shouldn't have been):

> <img width="429" alt="image" src="https://github.com/LuteOrg/lute-v3/assets/1637133/074c2154-f239-4ea4-ba20-6c096ef1a003">

**Comment by jzohrab** [comment]
Thanks again @LangNerd23 -- Lute was doing too much cleanup when the old parent was getting removed from the record.  Currently working on this, have an initial fix, and hope to have it sorted out soon.

**Comment by jzohrab** [comment]
Have a fix for this now, the link is maintained even on parent change.  e.g. repeating the above example:

<img width="400" alt="image" src="https://github.com/LuteOrg/lute-v3/assets/1637133/79c7b354-f66c-487a-9613-ec05d1477250">

**Comment by jzohrab** [comment]
Fix merged into develop, will be in next launch.

**Comment by jzohrab** [comment]
Hi @LangNerd23 -- I believe that this has been fixed with the launch of 3.4.3 (just now).  I'll close this issue -- please re-open a new one if you run into more problems with this, and reference this if needed.  Cheers and thanks!
