### ISSUE TITLE
Copy-to-clipboard doesn't work across multiple lines

### ISSUE THREAD

**Issue by bwkimmel** [LuteOrg/lute-v3#427]
**Description**

I cannot copy multiple lines of text to the clipboard.

**To Reproduce**

Steps to reproduce the behavior, e.g.:

1. Import a book.
2. Highlight multiple lines of text from the clipboard. Note that the UI *does* allow you to highlight multiple lines.
3. Press `CTRL+C` to copy the text.
4. Open another application (e.g., a text editor), and paste the contents into that application. Only one of the lines highlighted in step (2) will appear.

**Screenshots**

Highlighted text (step 2):

![image](https://github.com/LuteOrg/lute-v3/assets/534844/97bfb27f-b02c-4a46-b31b-7782f7b23344)

Copied text (step 3-4): 평일에는 동네에 있는 체육관에서
Expected: two lines of text should have been copied.

**Extra software info, if not already included in the Description:**

- OS (e.g., iOS, windows): Windows 11 Pro
- Browser (e.g., chrome, safari): Brave 1.66.110
- How you've installed Lute (Docker, python, source): Python
- Version: 3.3.2

**Comment by jzohrab** [comment]
Thanks @bwkimmel .  I mentioned this in #428 - Lute thinks each separate line is a standalone sentence, which is why the copy seems busted.  I'll have to see if there's a good solution for this, it gets tricky!

Until a decent solution is written, my hack workaround for you would be to edit the imported files so that each sentence is on the same line.

**Comment by jzohrab** [comment]
Looking at this again, thought it would be quick.   The manual at https://luteorg.github.io/lute-manual/usage/keyboard-bindings.html says:

```
c	Copy the sentence of the current word to the clipboard
Shift + c	Copy the paragraph of the current word to the clipboard
```

There's no "control-C" shortcut.

so it's a bit different than what this issue requests.  But as mentioned, the UI does allow highlighting across lines, so it would feel logical (to me) for the copy to copy everything that was highlighted ... maybe a new "control-C" shortcut would be the clearest thing to do.

**Comment by jzohrab** [comment]
Hi again.  I'm implementing "copy full page" as part of #495 , which should _mostly_ suffice.

I forgot about an undocumented feature: if you hold down shift while mouse-down-dragging across multiple sentences:

> <img width="622" alt="image" src="https://github.com/user-attachments/assets/541c61b8-2ae2-4463-9705-95af85fc9db6">

when you release the mouse, Lute says "Copied to clipboard!" and then you can paste it:

```
unknown" - according to Lute, this is the first time you're seeing these words.
You can click on a word, and create a definition. For example, click on this word: elephant.
When the form pops up in the right-hand frame, a dictionary
```

**Comment by jzohrab** [comment]
I added a page to the manual about copying text, I thought it was needed.  Thanks for the nudge.  :wave:

https://luteorg.github.io/lute-manual/usage/reading/copying-text.html
