### ISSUE TITLE
Define Parent Terms without them being in the text

### ISSUE THREAD

**Issue by Kayzi0** [LuteOrg/lute-v3#435]
**Is your feature request related to a problem? Please describe.**

Currently, you can only define a parent term if that term can be found somewhere in the current text, or if it is already in your list of terms. This is impractical if, for example, you encounter a conjugated verb and its inifinitive is not in the text. If you try to manually type in the infinitive, it does not save the parent at all.

If you want to link it to its infinitive, you need to go to the terms tab, create the term manually, and then link it to that term.

**Describe the solution you'd like**

Allow manual definition of a parent term

**Comment by jzohrab** [comment]
You can save a new parent — you have to Return or Enter after entering the new parent text to convert the parent text to a “tag”.  Does that make sense?  Give it a shot.  There’s an issue to auto convert the parent to a tag which will fix this so it behaves better, as I agree it can be confusing.

**Comment by jzohrab** [comment]
Here's an example: the term "arrow" doesn't exist -- if I hit "save" now, "arrow" hasn't been converted into a tag, so the term wouldn't be created:

> <img width="422" alt="image" src="https://github.com/LuteOrg/lute-v3/assets/1637133/acaf4209-31cf-4a45-83f8-e2bb26c08376">

Here I've hit the Return key while in the parent field, and "arrow" will be created as a term when I hit Save:

> <img width="409" alt="image" src="https://github.com/LuteOrg/lute-v3/assets/1637133/347ead0f-9753-42ad-8972-575da6bb09d5">

This is related to issue https://github.com/LuteOrg/lute-v3/issues/324 .  I believe it's a duplicate, so I'll close this one.  I agree that the current UI isn't really intuitive -- it's tripped me up too, and I wrote the thing.

**Comment by jzohrab** [comment]
Thanks for the issue @Kayzi0 , I hope to get this fixed at some point!
