### ISSUE TITLE
Books and Terms are gone after I used Chrome's "Install page as app"

### ISSUE THREAD

**Issue by lef-est** [LuteOrg/lute-v3#446]
**Description**

Books and Terms are gone after I used Chrome's "Install page as app". It happens probably because Chrome "apps" handle storage differently, but now how can I get the data back into this "app-ified" Lute? It's still somewhere on my disk right?

**Screenshots**

![image](https://github.com/LuteOrg/lute-v3/assets/9643637/934b883e-5e77-458a-b41f-e0a0a393b059)
Choosing "Open in Chrome" does nothing. I have not tried "uninstalling" app yet because I do want to use Lute in this mode. It is more immersive without having to use full screen mode.

**Extra software info, if not already included in the Description:**
- The "Languages" settings still show that I have X number of books or terms associated with each language, and thankfully all my settings are intact.
- LUTE 3.4.3, Windows pip install
- Chrome 125.0.6422.142

**Comment by lef-est** [comment]
FYI I uninstalled to troubleshoot some other issue and the books are back. Maybe you'd like to enhance the experience or add a big warning in your manual or tutorial :)

**Comment by jzohrab** [comment]
Hey there.  Hm, this is interesting -- but you'd still need to run Lute's server first, the app alone wouldn't suffice.  I'm going to close this issue for now just to manage the backlog.  Maybe in future someone else will solve this problem.  I do want installs to be easier but have no idea how to do that and still allow for things like plugins etc ... it's a tough problem.  Thanks for the notes!

**Comment by lef-est** [comment]
Oh it's totally cool, just saying you may want to add a warning somewhere.

> you'd still need to run Lute's server first, the app alone wouldn't suffice. 

I wasn't expecting to skip clicking on the .bat script. I just like not seeing my Chrome address bar, while still have access to my taskbar unlike the fullscreen mode, no biggie
