### ISSUE TITLE
Increased length for URL field needed

### ISSUE THREAD

**Issue by LangNerd23** [LuteOrg/lute-v3#449]
**Description**

When studying a language that doesn't use the latin alphabet the following might happen:
Import of webpage fails with warning "Field cannot be longer than 255 characters.".
1) The warning is not clear about which field it refers to.
2) Still I found the URL field to be problematic.

From what I understood: Such non-latin URLs are sometimes transformed when doing copy/paste in general - and therefore as well when copied to  Lute (but I don't understand why). 
I realize, this in not a lute problem in the first place. Still I would suggest to increase the maximum length for the URL field heavily (1000?) then this problem shouldn't occur anymore.

**To Reproduce**

Steps to reproduce the behavior, e.g.:

1. Go to Import book from webpage
2. Enter a URL received from elsewhere(!!) like 

> https://www.dw.com/el/η-ελλάδα-παράδειγμα-για-τη-γερμανία-με-το-εξαήμερο-εργασίας/a-68934569

 (with direct copy and paste from text in edit window here in github, there is no problem;
 however, when opening this page and the coping from there, the problem seems to be reproducable as follows)

3. Already after entering the URL is pasted as 

> https://www.dw.com/el/%CE%B7-%CE%B5%CE%BB%CE%BB%CE%AC%CE%B4%CE%B1-%CF%80%CE%B1%CF%81%CE%AC%CE%B4%CE%B5%CE%B9%CE%B3%CE%BC%CE%B1-%CE%B3%CE%B9%CE%B1-%CF%84%CE%B7-%CE%B3%CE%B5%CF%81%CE%BC%CE%B1%CE%BD%CE%AF%CE%B1-%CE%BC%CE%B5-%CF%84%CE%BF-%CE%B5%CE%BE%CE%B1%CE%AE%CE%BC%CE%B5%CF%81%CE%BF-%CE%B5%CF%81%CE%B3%CE%B1%CF%83%CE%AF%CE%B1%CF%82/a-68934569

4. After clicking "Import" and in the next window "save"
5. See error "Field cannot be longer than 255 characters."

**Extra software info, if not already included in the Description:**

- OS: Windows (tried on android as well)
- Browser: checked with firefox and chrome
- How you've installed Lute (Docker, python, source): pip
- Version: 3.4.3

**Comment by jzohrab** [comment]
Good catch, thanks @LangNerd23 .

**Comment by jzohrab** [comment]
This was an arbitrary restriction but I don't see any problem in increasing it.  Trying it out.

**Comment by jzohrab** [comment]
Fixed in `develop`, will be in the next launch.

**Comment by jzohrab** [comment]
Launched in 3.5.0. :tada:
