### ISSUE TITLE
Allow use of offline dictionaries or APIs for prepopulation such as Freedict

### ISSUE THREAD

**Issue by stereotypy** [LuteOrg/lute-v3#452]
**Is your feature request related to a problem? Please describe.**
I'm coming from trying out LWT which seems like it's not under active development and a bit dated at this point. I didn't like that to add terms, it basically created a popup to a dictionary and you'd have to manually enter the translation.

**Describe the solution you'd like**
Freedict (https://freedict.org/downloads/) has a number of free offline dictionaries that could be used for prepopulation if there is an issue finding a free dictionary API (maybe there is one, I don't know). 

**Describe alternatives you've considered**

Typing everything in manually becomes cumbersome. I could cobble together my vocab plus some A1+A2 basic word lists for import via CSV but it would take a long time and is overwhelming.

**Comment by jzohrab** [comment]
Thanks @stereotypy .  This feels like a dup of #228, I'll copy the description above over there.  Cheers!
