### ISSUE TITLE
Extra empty error messages in Language edit error.

### ISSUE THREAD

**Issue by cblanken** [LuteOrg/lute-v3#458]
**Description**
It looks like the edit Language page/form renders some extra empty error messages when there is an error after saving. It's probably just some unnecessary styling or a loop going over all the possible error messages and not filtering out the inactive ones.

**To Reproduce**
1. Go to 'Language Edit'
2. Pick a language
3. Add a Term dictionary that's missing the "###"
4. See error screenshot below

**Screenshots**
![image](https://github.com/user-attachments/assets/c2a8837b-8831-49be-9e7c-b07ea68caef2)

**Comment by jzohrab** [comment]
Thanks!  The flask error messages were uglier to manage than I'd expected, perhaps due to my lack of experience with flask subforms etc.  This _should_ be an easy fix, will take a look.

**Comment by jzohrab** [comment]
Thank you, fixed in `develop`.  The code feels a bit sloppy, but ... works.  (I feel so dirty saying that.)

**Comment by jzohrab** [comment]
Launched in 3.5.1.
