### ISSUE TITLE
dictionary iframes can steal focus from lute

### ISSUE THREAD

**Issue by s-cork** [LuteOrg/lute-v3#464]
**Is your feature request related to a problem? Please describe.**

I have a dictionary, en.openrussian.org, when opened in lute, it steals focus.
This makes changing word status annoying.
I click on a word, then try to hit a number, but the iframe has stolen the focus (it sets it to an input element), and so typing the number changes the input text.

**Describe the solution you'd like**

the iframe should not steal focus

**Describe alternatives you've considered**

na

**Additional context**

I have a fix locally for this.
Instead of calling activate straightaway, i call activate after the iframe's load event has fired.
This way the iframe can't steal focus on load (since it has display none, until we call activate)
It works pretty well for my use case and I can't see that it would negatively impact other iframe dictionaries.

Happy to write a PR.

**Comment by jzohrab** [comment]
Hi there, thanks for the issue!  I think someone already has a PR for this from a few days ago I need to test and merge.  Will close this if so. Cheers!

**Comment by jzohrab** [comment]
Hi @s-cork , PR #459 actually dealt with this issue already, so I'll close this one.  Thank you again!

**Comment by jzohrab** [comment]
Launched in 3.5.1.
