### ISSUE TITLE
Not possible to update unknown words using bulk import (without making them known)

### ISSUE THREAD

**Issue by s-cork** [LuteOrg/lute-v3#465]
**Description**

It's currently not possible to update unknown words without unknown words becoming known words

**To Reproduce**

Create some unknown words as a csv
upload the words using bulk import (create new terms, set new terms to unknown)
observe you now have hover translations for these words and they remain unseen
upload the words again using bulk import
observe these unknown words now all have a status of 1

---

I was playing around with trying to bulk import an initial dictionary of terms for my target language.
there was some trial and error as I improved the formatting or made mistakes
But i couldn't update unknown words because in the code, uploading an existing word, if its status is 0 changes it to 1.

This was quite frustrating, particularly given i was importing hundreds of thousands of terms.

I think - if it's a bulk import, then the status should not change when updating unless the status is included in the csv.

**Comment by jzohrab** [comment]
Thank you, I agree it shouldn’t change it. Sorry about that!  Should be a quick fix.

**Comment by jzohrab** [comment]
Thanks @s-cork , I changed this in `develop`, it makes more sense and the code is clearer too.  Will be in the next launch, apologies for the hassle.  Cheers!

**Comment by jzohrab** [comment]
Launched in 3.5.1.
