### ISSUE TITLE
3.5.1: Dictionaries no longer loading

### ISSUE THREAD

**Issue by jamesdeluk** [LuteOrg/lute-v3#469]
Upgraded to 3.5.1, dictionaries typically don't load. Perhaps 1 time in 10 they load.

Downgraded to 3.5.0, they load again every time.

Specifically, https://korean.dict.naver.com/koendict/#/search?query=### and https://en.dict.naver.com/#/search?query=###

Possibly related to https://github.com/LuteOrg/lute-v3/issues/464 and https://github.com/LuteOrg/lute-v3/pull/459?

**Comment by jzohrab** [comment]
Well that's a drag, sorry about that!  I tested with some other dicts and it was fine, but obv. it's no good.  So I'll revert that change and maybe we can work something else out.  Should be out soon, thanks.

**Comment by jamesdeluk** [comment]
It happens 😄 Maybe someone else can double-check to ensure it's not just an issue I'm having.

**Comment by cblanken** [comment]
> It happens 😄 Maybe someone else can double-check to ensure it's not just an issue I'm having.

@jamesdeluk I'm having trouble replicating this. Could you post what browser you're using and the version?

For me they load immediately, but it's possible they won't display immediately if your connection is slow. Do they show up if you wait a while (10-15 seconds) after selecting a term or does the dictionary pane just keep the background color without any indication of loading?

Also if you have any other dictionaries failing to load please post them as well so I can check them. Thanks.

**Comment by jamesdeluk** [comment]
Firefox 129.0.2 (64-bit) on Windows 11.

I've just re-upgraded to 3.5.1 and the issue persists.

Waiting for extended periods doesn't work.

Other dictionaries (e.g. https://en.wiktionary.org/wiki/###) load fine.

The network does do a GET request for the URL, but nothing loads.

When I click off and on again, I get `en.dict.naver.com content already loaded.` (or `korean.dict.naver.com content already loaded.`) in the console, so it thinks it's loaded.

Downgrading to 3.5.0, everything loads again instantly. After the GET request, there are a bunch more as the page loads.

**Comment by jzohrab** [comment]
Hey @jamesdeluk , I'm going to back out the change in 3.5.1.  Too bad :-/  but it's causing other issues too.  @cblanken spent a whack of time trying to come up with workarounds, but no dice.  Thanks for the detail!

**Comment by jzohrab** [comment]
Change reverted, this should be fixed when 3.5.2 is launched.  Thanks @jamesdeluk and @cblanken , cheers!

**Comment by jzohrab** [comment]
Launched in 3.5.2
