### ISSUE TITLE
[Enhancement] Improve the new implementation of keyboard focus introduced in 3.5.1

### ISSUE THREAD

**Issue by lef-est** [LuteOrg/lute-v3#471]
**Description**
1. When I click on a word I usually immediately place the cursor in the translation area.
2. As I'm about to start typing, the keyboard focus went to the reading pane.
3. Unaware of the loss of focus, or driven by muscle memory, I still start to type, accidentally triggering some keyboard shortcut, which usually ends in refreshing the whole page.

**Problem**
Keyboard focus should remain in the translation area if the cursor is already there.

**Comment by jzohrab** [comment]
Thank you, I think I have to remove that focus work, it had some good sides but also some bad as you're finding.  Thanks for the issue.

**Comment by jzohrab** [comment]
I've backed out #459 in the `develop` branch, so this fix will be launched with 3.5.2, which will likely be out soon-ish.  Thanks again @lef-est :wave:

**Comment by jzohrab** [comment]
Launched in 3.5.2, should be fixed now.
