### ISSUE TITLE
Startup script references nonexistent function

### ISSUE THREAD

**Issue by vpzomtrrfrt** [LuteOrg/lute-v3#479]
**Description**
pyproject.toml defines a "lute" script pointing at "lute.main:start", but lute.main no longer has a `start` method.

```
Traceback (most recent call last):
  File "/home/colin/tmp/venv/bin/./lute", line 5, in <module>
    from lute.main import start
ImportError: cannot import name 'start' from 'lute.main' (/home/colin/tmp/venv/lib/python3.12/site-packages/lute/main.py). Did you mean: '_start'?
```

**To Reproduce**

Steps to reproduce the behavior, e.g.:

1. Install lute3 via pip.
2. Try to run `lute`

**Extra software info, if not already included in the Description:**

- OS (e.g., iOS, windows): Gentoo Linux
- Browser (e.g., chrome, safari): n/a
- How you've installed Lute (Docker, python, source): pip
- Version: 3.5.2 and master

**Comment by jzohrab** [comment]
Thanks, this should be a fast fix.

**Comment by jzohrab** [comment]
The manual says to use `python -m lute.main` :-) I never used the pyproject script entry point, but this is good.  Thanks for the catch.

**Comment by jzohrab** [comment]
Fixed in `develop`, will be in next launch.

**Comment by jzohrab** [comment]
Launched in `3.5.3`, should be fixed now, thank you!
