### ISSUE TITLE
Don't relayout page when adding term

### ISSUE THREAD

**Issue by vpzomtrrfrt** [LuteOrg/lute-v3#482]
**Is your feature request related to a problem? Please describe.**

Not sure if this is relevant for most languages, but I'm using Lute to study Japanese, and saving a term that spans multiple lines causes the text to rearrange to move it onto the same line

**Describe the solution you'd like**

I think I would prefer the text stay as is. For initial load it would be fine, but changing while I'm trying to read is jarring

**Describe alternatives you've considered**

Ignoring the problem

**Additional context**

Before:
![image](https://github.com/user-attachments/assets/888002f1-3e28-48f5-a198-edd99d19152c)

After:
![image](https://github.com/user-attachments/assets/7d140ee0-f3f8-4bde-a9d0-ab8db3acf9dc)

**Comment by jzohrab** [comment]
Thanks @vpzomtrrfrt - I agree it can be disconcerting.  It happens because the terms are wrapped in an HTML `<span>` tag ... I'll see if I can find a quick fix.  Maybe another smart person can chip in as well.  Cheers!

**Comment by jzohrab** [comment]
I'm not able to get this to work correctly, given my very limited CSS skills.  I've pushed a branch `wip_issue_482_page_layout_hack_css` to the repo with some hack work which got nowhere.

Below's an example using the tutorial:

> <img width="759" alt="image" src="https://github.com/user-attachments/assets/bf8a0a8f-c4a0-4239-9669-508bc797569b">

The text "to navigate" is a multiword term, and is rendered as a `<span>` element: `<span id="ID-53-3" class="textitem ..." ...>to&nbsp;navigate</span>`  .  The `textitem` class is defined in the lute/static/css/styles.css:

```
/* A word shown in the reading pane. */
span.textitem {
    font-size: 16px;
    color: var(--font-color);
    display:inline-block;
```

I've tried various hacks for the `display`, `word-wrap`, and `white-space` css attributes for the textitem class, as well as various things for the enclosing div.  I couldn't get the textitem to break across different lines.

The `<span>` elements are necessary for Lute to properly handle clicks, drags, etc.

Maybe someone with better CSS skills than I can suggest fixes.

**Comment by jzohrab** [comment]
ok, I think this is fixed, which is nice.

e.g., tutorial excerpt:

> <img width="776" alt="image" src="https://github.com/user-attachments/assets/d296a289-db7d-460d-96c1-f27a5d60d991">

new multiword term added, wraps to next line:

> <img width="736" alt="image" src="https://github.com/user-attachments/assets/255baee9-ad84-4ba3-b16c-5f37a8593e37">

Japanese example:

> <img width="734" alt="image" src="https://github.com/user-attachments/assets/3a1cf85d-e5d5-4e01-8395-528e0bffb789">

**Comment by jzohrab** [comment]
Fixed in `develop`, will be in the next launch.

**Comment by jzohrab** [comment]
Launched in `3.5.3`, should be fixed now, thank you!
