### ISSUE TITLE
Specific page with bad rendering

### ISSUE THREAD

**Issue by Mycheze** [LuteOrg/lute-v3#489]
**Description**

This mostly isn't an issue anymore, but on a specific page I was reading today, any time I hovered over something, the page would freak out and resize. It was very annoying. Since it hardly happens anymore, I figured this specific page might be useful.

**To Reproduce**

Import the page and read/add terms as normal

**Screenshots**

[weirdlutepage.txt](https://github.com/user-attachments/files/17269920/weirdlutepage.txt)

**Extra software info, if not already included in the Description:**

- OS (e.g., iOS, windows): Linux
- Browser (e.g., chrome, safari): Chromium
- How you've installed Lute (Docker, python, source): Python
- Version: 3.2.5

**Comment by jzohrab** [comment]
Hey @Mycheze -- I think I'll need your full db to look into this, and maybe even a short screencast if possible.  I imported, set all to known, and everything looked ok to me even on hover.

![image](https://github.com/user-attachments/assets/d87b4512-cc81-4783-ba7b-519210e83211)
_Me dijo que funcionaría sin problemas._

**Comment by jzohrab** [comment]
Closing due to lack of response and unable to reproduce, please reopen if this is still an issue!
