### ISSUE TITLE
Change default port

### ISSUE THREAD

**Issue by cyugao** [LuteOrg/lute-v3#497]
Hi this is very minor, but for macOS users port 5000 is typically occupied by the system. See for example [this post](https://www.reddit.com/r/perl/comments/10p8p39/macos_port_5000_mystery_solved/)
It would be nice if port 5000 could be avoided.

**Comment by jzohrab** [comment]
Hi there!  You can specify a different port using the port startup flag.

**Comment by jzohrab** [comment]
Ref https://luteorg.github.io/lute-manual/usage/starting-and-stopping.html#pythonpip-startup-options

**Comment by jzohrab** [comment]
@cyugao - but you're right, it should be a better default port.  Can you let me know what a good port number is that works in general for Windows/Mac/Linux variants?

**Comment by cyugao** [comment]
Yes, that's my intention. I guess whatever port would work. It's just that 5000 happens to be taken by MacOS system. Of course if in use we can always fall back to 5001, etc.
See discussions [here](https://www.reddit.com/r/webdev/s/0yyJZySbk2) for example.

**Comment by jzohrab** [comment]
“Whatever port” — hopefully you can look into it and let me know what works on all machines.

(I’m asking instead of finding out myself because I need to figure out how to enlist more user support to solve problems for me, which would be immensely helpful!)

**Comment by cyugao** [comment]
I think 5001 is fine. Or maybe a random port like what you have in the doc 9876.

**Comment by jzohrab** [comment]
https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

> <img width="972" alt="image" src="https://github.com/user-attachments/assets/e4a08400-1773-4d02-8b36-f7e26604dae0">

5000 has lots of users, including Mac (which I ran into myself).  5001 does look like a better choice, let's go with that.  Thanks :-)

**Comment by jzohrab** [comment]
Launched in 3.5.7.
