### ISSUE TITLE
Popup even when ignored

### ISSUE THREAD

**Issue by LangNerd23** [LuteOrg/lute-v3#500]
**Description**

Not sure if I would call it a bug, but simply: When a term that has a not and has status ignored, the pop up doesn't work onmouseover (or touch in case of mobile). As briefly talked about on discord, there is no reason why it should NOT be shown, it rather seems that the use case was not clear.

Use case in my case: Studying a language with nonlatin script. So I often put there latin transcription of names (people, places, etc.). This helps, in case I am unsure what it is. Still I keep those to ignore, as it is not vocabulary I want to learn.

(I skip the other sections of the form as I guess this is self-explaining.)

**Comment by jzohrab** [comment]
Thanks @LangNerd23 , fixed in `develop`, this makes sense to me.  If you've added data, you should see it, even if you're ignoring the term for various reasons.

**Comment by jzohrab** [comment]
Launched in 3.5.7.
