### ISSUE TITLE
can not open lute after installing 

### ISSUE THREAD

**Issue by jefflou** [LuteOrg/lute-v3#512]
**Description**
i tried to install lute on my win10 pc. after installing i got the error message
 "Error during startup:
Type: <class 'PermissionError'>
[WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。

Please check your setup and try again.
Ask for help on Discord, or report an issue on GitHub.
Additionally, help is available with --help."
**Screenshots**

![image](https://github.com/user-attachments/assets/d3b0234f-3d45-4b77-9144-177e7b2183af)

- Version: 3.5.9

**Comment by jzohrab** [comment]
Hello @jefflou , thanks for the issue.  There a few things to try:

* Try running with the `--local` flag: `python -m lute.main --local`
* Try a different port other than 5001: `python -m lute.main --local --port 9876`  (9876 is just an example)

Let me know how it goes!

**Comment by jefflou** [comment]
thank you for your good advice .i can open lute  after using "python -m lute.main --local"

**Comment by jzohrab** [comment]
Ah super.  You might still want to get the 0.0.0.0 address working, in case you want to use Lute from a phone or tablet.  But the "local" flag lets it run without problem on your computer.  Cheers and best wishes!
