### ISSUE TITLE
(Bug ?) The titles of books marked as completely read do not display the current page anymore

### ISSUE THREAD

**Issue by Inquisitor-Ignotorum** [LuteOrg/lute-v3#517]
Configuration: Windows 10, Chromium-based browser, Lute v. 3.6.0 installed via pip

Hello. I do not know whether this is intentional, but I wanted to mention it just to be sure. When you reach the end of a book and click the tick named "Mark as read", the book's title will then have a green tick to its left, in the "Home" screen and in the "Book archive" screen, but the current page will not be displayed any more. This situation is the same regardless of whether the book is in the "Home" screen of in the "Book archive" screen. Even when I reach the end of another page and click on that page's "Mark as read" arrow, the current page will still not be displayed next to the book's title in the "Home" screen and in the "Book archive" screen.

When I finish a book, I always click on that tick in the book's last page, and I then archive the book. Sometimes, however, for various reasons, I like getting back to books which I have already finished reading, and it would be nice to be able to see the current page in the book's title in the "Home" screen and in the "Book archive" screen, just to know where I left off. I have included an image to clearly show what I mean.

Thank you for your time, and thank you for your amazing software.

![1](https://github.com/user-attachments/assets/ccd75f28-10c0-4216-91a7-f71d22b526ee)

**Comment by jzohrab** [comment]
Ah I thought it already did that, so that's a bug, thank you!

**Comment by jzohrab** [comment]
Confirmed, below I'm on page 5/6 of the tutorial:

> <img width="283" alt="image" src="https://github.com/user-attachments/assets/616f142c-a7a4-4fcf-ae4a-71763e1df46c">

**Comment by jzohrab** [comment]
Fixed in `develop`, thanks @Inquisitor-Ignotorum :

> <img width="243" alt="image" src="https://github.com/user-attachments/assets/ea8690a3-c281-426a-869c-9298b06dc9c8">

Will be launched soon.

**Comment by jzohrab** [comment]
Released in 3.6.1.
