### ISSUE TITLE
Support for offline dictionaries or instant definitions

### ISSUE THREAD

**Issue by sabretou** [LuteOrg/lute-v3#521]
**Is your feature request related to a problem? Please describe.**

Hello! I'm exploring Lute coming from [Vocab Tracker](https://www.vocabtracker.com), and one thing I miss is instant translations/definitions. 

As I understand it, in Lute, there are no pre-filled definitions, and you have to copy-paste your own definitions from an external dictionary. In my use case, I simply determine how well I know a word's meaning, and assign it a level. I do not intend to bother with assigning data to each word within Lute itself.

However, when you click on a word, loading an online dictionary for each new word can take a second or two (on my connection, at least), and that's enough to break my immersion when reading.

**Describe the solution you'd like**

Allow installing an offline .tsv dictionary (such as the ones used by [LinguaCafe](https://github.com/simjanos-dev/LinguaCafe/releases/tag/dictionaries)), to provide instant definitions for selected words, while in the meantime also loading the embedded online dictionary (if so configured).

**Describe alternatives you've considered**

I'm not sure what solution Vocab Tracker uses to be so efficient, but that! I think it uses some translator service, but whatever it is, it loads meanings instantly when selecting words or even phrases.

**Additional context**

That's all! Thank you!

**Comment by jzohrab** [comment]
Hi @sabretou , thanks very much for the issue and your notes.  This has been requested before, but your detail helps, so I've copied the information here to the older issue (#228), and I'll close this one as a duplicate.  Cheers!

**Comment by jzohrab** [comment]
Hi @sabretou - could you give some detail for the questions I asked in #228?  Cheers!
