### ISSUE TITLE
Allow listing of unknown terms in term listing, default to min status 1

### ISSUE THREAD

**Issue by jzohrab** [LuteOrg/lute-v3#544]
People can add status=0 terms, but currently can't see them; they should be able to, it's just data.

Considerations/steps:

- [x] add to filter combo box
- [x] if status lower bound isn't explicitly set, should default to 1
- [x] add test?

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the term index page to include status=0 in the filter options and adjusted the default behavior to show all statuses including 0 when no specific status range is set.

You can review changes in this commit: https://github.com/wwqwq2313/LuteOrg-lute-v3-544/commit/5fc647e4df7e932c449924db03f03aa056815634.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by jzohrab** [comment]
Thank you, @wwqwq2313 !  I'll take a look.

**Comment by jzohrab** [comment]
In progress, running tests.

**Comment by jzohrab** [comment]
Fixed in `develop`

**Comment by jzohrab** [comment]
Launched in 3.8.0.
