### ISSUE TITLE
little bug using Bing translator

### ISSUE THREAD

**Issue by edwardyeung** [LuteOrg/lute-v3#546]
**Description**

I was trying to add Bing translator.

**To Reproduce**

Steps to reproduce the behavior, e.g.:

1. Go to 'Language'
2. add new dictionary, choose embedded, and click the little arrow to test, you will find everything is normal
3. Go to book, and click any words to translate via Bing, then the error shows up.

**Error logs**

Version: 3.7.0
You were on: http://192.168.50.215:5001/read/17
You were trying to access: http://192.168.50.215:5001/bing/search/4/find/https://www.bing.com/translator%3Ftext=[LUTE]
![image](https://github.com/user-attachments/assets/c9cc09b1-b023-47b3-8e90-dc9e7df7d0f2)

**Other**
installed in OrangePi 3 LTS. Python 3.10

**Comment by jzohrab** [comment]
Hi @edwardyeung , thanks for the message. Can you paste the URL that you set up in the dictionary list for the language?  A screenshot is fine. Cheers!

**Comment by edwardyeung** [comment]
url:
https://www.bing.com/translator?text=[LUTE]

I thought the problem caused by the question mark at first, so I tried "https://www.bing.com/translator", and had no luck.

**Comment by jzohrab** [comment]
I think you need the from and to parameters as well. For example, here is from Thai to English:

`https://www.bing.com/translator/?from=th&to=en&text=[LUTE]`

**Comment by edwardyeung** [comment]
by the way, I don't know if you are interested or not.
I am an obsidian (a note taking app) user, there is a plugin for obsidian called custom frame which solves the problems of some websites forbidding using iframe and make users access google keep, google translate...etc

here is the plugin source. 
https://github.com/Ellpeck/ObsidianCustomFrames/blob/master/src/frame.ts

**Comment by edwardyeung** [comment]
> I think you need the from and to parameters as well. For example, here is from Thai to English:
> 
> `https://www.bing.com/translator/?from=th&to=en&text=[LUTE]`

Brilliant!

**Comment by edwardyeung** [comment]
> I think you need the from and to parameters as well. For example, here is from Thai to English:
> 
> `https://www.bing.com/translator/?from=th&to=en&text=[LUTE]`

sadly, still had no luck using the same url.
![image](https://github.com/user-attachments/assets/ec6ef378-42a1-4ca1-82ce-afce2e44dd86)

**Comment by jzohrab** [comment]
Well, this is annoying!  Back at my computer, trying further on my machine, and I have the same issue :-( .  It used to work, but I couldn't test it in CI so ... broken silently, which sucks terribly.  Thanks for the ping, there are some things that just can't be tested easily unless it's done manually (unless, of course, I just don't know what I'm missing).

Anyway, reproducing: For Spanish, I have the following as an embedded term dict:

> `https://www.bing.com/translator/?from=es&to=en&text=[LUTE]`

i.e.

> <img width="1328" alt="image" src="https://github.com/user-attachments/assets/3c535d33-763a-4d9f-a8db-c0eea51c2f84" />

and I got this error:

> <img width="719" alt="image" src="https://github.com/user-attachments/assets/a9a3b071-974d-4125-9b05-4c36e0dd3a51" />

Thank you @edwardyeung , I'll try to get a fix out very soon, as it's nice to have the embedded bing lookup.  Cheers!

**Comment by jzohrab** [comment]
OK, this is fixed in `develop` now.  Here's using Bing as a term lookup:

> <img width="70%" alt="Image" src="https://github.com/user-attachments/assets/030759d6-6c51-4c40-95f1-e8de64cb6514" />

and as a sentence lookup:

> <img width="70%" alt="Image" src="https://github.com/user-attachments/assets/4fb2e0a8-0e28-450f-a470-286e6b9194ea" />

**Comment by jzohrab** [comment]
Launched in 3.8.0.
