### ISSUE TITLE
Add language: Modern Chinese

### ISSUE THREAD

**Issue by fanyingfx** [LuteOrg/lute-v3#83]
- Add modern chinese parser that can detect Chinese mutiple-character-words and some test cases.
- Add langauge config and  the story.

By default using the [pkuseg](https://github.com/lancopku/pkuseg-python) for parsing Chinese, if user want a more accurate parser, can install [hanlp](https://github.com/hankcs/HanLP) by pip.

Have  created a [PR ](https://github.com/jzohrab/lute-v3/pull/69) for this

**Comment by GrimPixel** [comment]
Seriously, it is not called “Modern Chinese”. Maybe you mean “Mandarin Chinese”. Other Chinese dialects have largely different vocabularies.

**Comment by M-Biggles** [comment]
> Seriously, it is not called “Modern Chinese”. Maybe you mean “Mandarin Chinese”. Other Chinese dialects have largely different vocabularies.

We already have 'Classical Chinese'. So, in that context, it's fair to say 'modern'. Probably best to not debate that stuff here. :)

**Comment by jzohrab** [comment]
Mandarin is added :-), old issue, closing.
